### ISSUE TITLE
compare datata and OSM city coordinates

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/ru-cities#7]
Our city dataset is based on dadata output for city coordinates. We also queried OSM (in geocoding folder).

Do `assets/towns.csv` and `geocoding/coord_osm.csv` have similar coordinates?

@TMichaelan - can you please look?

**Comment by TMichaelan** [comment]
@epogrebnyak Yes, I already did, but I don't have access to the repository to send the script. Everything returns false there because the coordinates have a little bit different everywhere.
